openapi: 3.0.3
info:
  title: Tinyval
  description: |
    Hash table service for storing and retrieving values (blobs) using their SHA-256 hashes as keys.
  version: 0.1.0
paths:
  /blobs/{hash}:
    get:
      tags:
        - Storage
      summary: Get blob
      parameters:
        - $ref: "#/components/parameters/hashPathParam"
      responses:
        "200":
          description: Successful Response
          content:
            application/octet-stream: {}
        "404":
          $ref: "#/components/responses/NotFound"
        "422":
          $ref: "#/components/responses/UnprocessableEntity"
    put:
      tags:
        - Storage
      summary: Put blob
      parameters:
        - $ref: "#/components/parameters/hashPathParam"
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/Body_put_blobs_hash"
        required: true
      responses:
        "200":
          description: Successful Response
        "422":
          $ref: "#/components/responses/UnprocessableEntity"
    head:
      tags:
        - Storage
      summary: Check if blob exists
      parameters:
        - $ref: "#/components/parameters/hashPathParam"
      responses:
        "200":
          description: Successful Response
        "404":
          $ref: "#/components/responses/NotFound"
        "422":
          $ref: "#/components/responses/UnprocessableEntity"
components:
  schemas:
    Body_put_blobs_hash:
      required:
        - blob
      type: object
      properties:
        blob:
          type: string
          format: binary
    HTTPError:
      type: object
      required:
        - status
        - error
      properties:
        status:
          type: integer
        error:
          type: string
        detail:
          type: string
  parameters:
    hashPathParam:
      name: hash
      in: path
      required: true
      description: SHA-256 hash
      example: 38bf13ef9985026a3fb71fea9ae95826cf8d84b02f300d481ba90a61f35504a6
      schema:
        pattern: ^[0-9a-f]{64}$
        type: string
        description: SHA-256 hash
  responses:
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/HTTPError"
    UnprocessableEntity:
      description: Unprocessable Entity
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/HTTPError"